services:
  mini-projects:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./data/kleinanzeigen-map:/app/kleinanzeigen-map/data
      - ./data/fuel-tracker:/app/fuel-tracker/data
      - ./data/recipe-book:/app/recipe-book/data
    networks:
      - moritz_web

networks:
  moritz_web:
    external: true
